package soa.model;
// Generated Feb 20, 2024, 10:34:03 AM by Hibernate Tools 6.1.3.Final

/**
 * Person generated by hbm2java
 */
public class Person implements java.io.Serializable {

	private int id;
	private String name;

	public Person() {
	}

	public Person(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
